### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by JeffFosterUK** [stargo/irssi2telegram#10]
Can't locate Net/HTTPS/NB.pm in @INC (you may need to install the
          Net::HTTPS::NB module) (@INC contains: /root/.irssi/scripts
          /usr/share/irssi/scripts /usr/lib/x86_64-linux-gnu/perl/5.22
          /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1
          /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22
          /usr/share/perl5 /usr/share/perl/5.22 /usr/local/lib/site_perl .) at
          /root/.irssi/scripts/telegram.pl line 25.
19:57 BEGIN failed--compilation aborted at /root/.irssi/scripts/telegram.pl
          line 25.
:((((((((((((((((((((((((((((

**Comment by knilch0r** [comment]
You need the Net::HTTPS::NB module for a non-blocking https client in perl. It's available on [CPAN](http://search.cpan.org/~oleg/Net-HTTPS-NB-0.15/lib/Net/HTTPS/NB.pm).

On a Debian-based system, the simplest approach probably is to install the `libnet-https-nb-perl` package (using `apt-get install libnet-https-nb-perl`). If your system doesn't have a package, you might succeed in using one of the [CPAN installers](http://www.cpan.org/modules/INSTALL.html).

**Comment by JeffFosterUK** [comment]
Thank you, thank you, thank you!!!! :)
